package syntax.annotations.example_5

class MyClass

// #1 @JvmField on the top-level property
// The same as Java expression:
//      public static final MyClass prop_1 = new MyClass();
/**
 * Exposes a Kotlin property as a field in Java
 *
 * If modifier is:
 *      "val" - no getter
 *      "var" - no getter/setter
 * will be generated by a compiler
 */
@JvmField
val prop_1 = MyClass()


// #2 @JvmField on the property inside the object
object MyObject {
    /**
     * @JvmField creates property static if it's used at the top level or inside the object.
     */
    @JvmField
    val prop_2 = MyClass()
}


// #3 @JvmField on the property inside the class
class MyWrapper {
    /**
     * @JvmField creates regular field
     */
    @JvmField
    val prop_3 = MyClass()
}
