package syntax.constructors.example_1

fun main() {
    // #1
    // val deposit = Deposit()

    // #2
    // val deposit = Deposit("", "some_deposit_id")
    // val deposit = Deposit("some_bank_id", "")
    /*val deposit = Deposit("some_bank_id", "some_deposit_id")
    println("Bank id: ${deposit.getBankId()} \nDeposit id: ${deposit.getDepositId()}")*/

    // #3
    val deposit = Deposit("some_bank_id", "some_deposit_id")
    println("Bank id: ${deposit.bankId} \nDeposit id: ${deposit.depositId}")
}

// #1 Get an empty 'primary constructor' generated by the compiler automatically
// class Deposit

// #2 Our own 'primary constructor' without 'val'/'var'.
/*class Deposit constructor(bankId: String, depositId: String) {
    private val bankId: String
    private val depositId: String

    init {
        require(bankId.isNotEmpty()) {
            "Invalid 'bank id' value."
        }
        require(depositId.isNotEmpty()) {
            "Invalid 'deposit id' value. "
        }
        this.bankId = bankId
        this.depositId = depositId
    }

    fun getBankId(): String = this.bankId
    fun getDepositId(): String = this.depositId
}*/

// #3 Our own 'primary constructor' with 'val'/'var'.
class Deposit constructor(val bankId: String, var depositId: String)